name: Deploy
on:
  push:
    branches:
      - workflow-deployer

env:
  PHP_VERSION: 8.3

jobs:
  build:
    uses: './.github/workflows/build.yaml'
    strategy:
      matrix:
        operating-system: [ ubuntu-24.04 ]
        php-version: [ '8.3' ]
        dependency-stability: [ prefer-stable ]

  deploy:
    runs-on: ubuntu-24.04
    needs: build
    environment: Production

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Setup PHP
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Restore vendor from cache
        uses: actions/cache@v4.0.2
        id: vendor-cache
        with:
          path: vendor
          key: ${{ runner.os }}-build-php${{ env.PHP_VERSION }}-${{ hashFiles('**/composer.lock') }}

      - name: Deploy
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          dep: deploy
