name: Test Laravel Github action
on:
  pull_request:
    branches:
      - main
      - develop

env:
  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  # See https://github.com/cc-fiae-2024/cc-fiae-2024/settings/secrets/actions
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_DATABASE: testing

jobs:
  build:
    uses: './.github/workflows/build.yaml'

  tests:
    needs: [build]
    # See https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job#standard-github-hosted-runners-for-public-repositories
    runs-on: ubuntu-24.04
    environment: testing

    strategy:
      matrix:
        operating-system: [ubuntu-24.04]
        # Limited by https://github.com/shivammathur/setup-php#github-hosted-runners
        php-version: [ '8.3' ]
        dependency-stability: [ prefer-stable ]

    name: P${{ matrix.php-version }} - ${{ matrix.dependency-stability }} - ${{ matrix.operating-system }}

    steps:
    - name: Download build artifact
      id: download-artifact
      uses: actions/download-artifact@v4.1.8
      with:
        # Pick up the folder from build.yaml Upload (name must match)
        name: eventguru-build-${{ github.run_id }}

    - name: List artifact directories
      run: |
        echo ${{ steps.download-artifact.outputs.download-path }}
        ls -R

    - uses: actions/checkout@v4.1.7

    - name: Start MySQL service
      run: sudo systemctl start mysql.service

    - name: Install PHP
      uses: shivammathur/setup-php@2.31.1
      with:
        php-version: ${{ matrix.php-version }}

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4.0.2
      id: actions-cache
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Cache PHP dependencies
      uses: actions/cache@v4.0.2
      id: vendor-cache
      with:
        path: vendor
        key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

    - name: Install PHP Dependencies
      if: steps.vendor-cache.outputs.cache-hit != 'true'
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Prepare Laravel Application
      run: |
        php -r "file_exists('.env') || copy('.env.example', '.env');"
        php artisan key:generate

    - name: Run Migrations
      run: php artisan migrate

    - name: Execute tests (Unit and Feature tests) via PestPHP
      run: php artisan test
