name: Test Laravel Github action
on:
  workflow_call: # Allow to be triggered by another workflow
  workflow_dispatch: # Allow for manual dispatch
  workflow_run:
    workflows:
      - "Build Laravel Github action"
    types:
      - completed

env:
  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  # See https://github.com/cc-fiae-2024/cc-fiae-2024/settings/secrets/actions
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_DATABASE: testing

jobs:
  laravel-tests:
    # See https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job#standard-github-hosted-runners-for-public-repositories
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: testing

    strategy:
      matrix:
        operating-system: [ubuntu-24.04]
        # Limited by https://github.com/shivammathur/setup-php#github-hosted-runners
        php-versions: [ '8.3' ]
        dependency-stability: [ prefer-stable ]

    name: P${{ matrix.php-versions }} - L${{ matrix.laravel }} - ${{ matrix.dependency-stability }} - ${{ matrix.operating-system}}

    steps:
    - name: Debug
      run: echo "Run-id ${{ github.event.workflow_run.id }} because ${{ github.event.workflow_run.conclusion }}"

    - name: Download build artifact
      uses: actions/download-artifact@v4.1.8
      with:
        # Pick up the folder from build.yaml Upload (name must match)
        name: public-folder
        # See https://github.com/actions/download-artifact#download-artifacts-from-other-workflow-runs-or-repositories
        run-id: ${{ github.event.workflow_run.id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Execute tests (Unit and Feature tests) via PestPHP
      run: php artisan test
