name: Test Laravel Github action
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  laravel-tests:
    # See https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job#standard-github-hosted-runners-for-public-repositories
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        operating-system: [ubuntu-24.04]
        # Limited by https://github.com/shivammathur/setup-php#github-hosted-runners
        php-versions: [ '8.3' ]
        dependency-stability: [ prefer-stable ]

    name: P${{ matrix.php-versions }} - L${{ matrix.laravel }} - ${{ matrix.dependency-stability }} - ${{ matrix.operating-system}}

    steps:
    - uses: actions/checkout@v4.1.7 # Even better: using @<commit-SHA>

    - name: Start MySQL service
      run: sudo systemctl start mysql.service

    - name: Install PHP versions
      uses: shivammathur/setup-php@2.31.1
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Get Composer Cache Directory 2
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - uses: actions/cache@v4.0.2
      id: actions-cache
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Cache PHP dependencies
      uses: actions/cache@v4.0.2
      id: vendor-cache
      with:
        path: vendor
        key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

    - name: Cache Node dependencies
      uses: actions/cache@v4.0.2
      id: node-cache
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

    - name: Install PHP Dependencies
      if: steps.vendor-cache.outputs.cache-hit != 'true'
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Install Node Dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm install

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Prepare Laravel Application
      run: php artisan key:generate --env=testing

    - name: Run Migrations
      run: php artisan migrate --env=testing

    - name: Build Frontend Assets
      run: npm run build

    - name: Execute tests (Unit and Feature tests) via PestPHP
      run: php artisan test
